var express = require('express');
var router = express.Router();
var Report = require('fluentreports').Report;

var routerMaker = function (db) {

  router.get('/', function (req, res, next) {
    res.render('app/index', { title: 'Dashboard', section: 'home' });
  });

  router.get('/login', function (req, res, next) {
    res.render('app/login', { title: 'Login' });
  });

  router.get('/employees/manage', function (req, res, next) {
    res.render('app/employees/manage', { title: 'Employees - Manage', employees: db.getEmployees(), section: 'employees' });
  });

  router.get('/employees/add/', function (req, res, next) {
    res.render('app/employees/add', { title: 'Employees - Add', section: 'employees' });
  });

  router.get('/employees/edit/:id', function (req, res, next) {
    res.render('app/employees/edit', { title: 'Employees - Edit', section: 'employees', employee: db.getEmployee(req.params.id) });
  });

  router.get('/reports/employees', function (req, res, next) {
    // Our Simple Data in Array format:
    var data = [];
    // Go through the database and get the actual data
    var employees = db.getEmployees();
    for (let i = 0; i < employees.length; ++i) {
      var employee = employees[i];
      // Each employee will have his name and a summary of the hours worked
      var hours = 0;
      for (let j = 0; j < employee.shifts.length; ++j) {
        var shift = employee.shifts[j];
        if (shift.out && shift.in) {
          // Convert the time from milliseconds to hours
          hours += Math.round((shift.out - shift.in) / 60 / 60 * 10) / 10;
        }
      }

      data.push([employee.first_name + ' ' + employee.last_name, hours]);
    }

    var send = function (err, report) {
      res.type('pdf');
      res.send(report);
    }

    var headerFunction = function(Report) {
      Report.print('Employee Hours Summary', {fontSize: 24, bold: true, align: 'center'});
      Report.newLine(2);
    };

    var footerFunction = function(Report) {
      Report.newLine(2);
      Report.print('Report Generated by Just Clock In', {fontSize: 10, bold: true, align: 'center'});
    };

    // Create a Report
    new Report('buffer')
      .data(data)
      .pageHeader(headerFunction)
      .pageFooter(footerFunction)
      .detail( [[0, 300],[1, 50]])
      .render(send);

    // res.render('app/reports/employees', { title: 'Reports - Employees', employees: db.getEmployees() });
  });

  return router;
};

module.exports = routerMaker;
